apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: kubric-api-gateway-hpa
  namespace: kubric-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: kubric-api-gateway
  minReplicas: 3
  maxReplicas: 15
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          averageUtilization: 65
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          averageUtilization: 75
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: kubric-api-gateway-pdb
  namespace: kubric-prod
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: kubric-api-gateway